### ISSUE TITLE
API tutorial

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/splash_page#26]
I think we need some kind of basic walkthrough for how to use the API. No video necessary -- just a step-by-step text how-to (maybe with a few screenshots?) should be sufficient. Michael, would you be willing to help me put this together at some point?

**Comment by aazaff** [comment]
This would be a good starting point. [Lab Exercise 3](https://github.com/paleobiodb/teachPaleobiology/blob/master/LabExercise3.md#paleobiology-database-api)

**Comment by aazaff** [comment]
Not going to do this, but I will note that the PaleoSociety is offering money so if a student ever wants to do this I would work with them.
