### ISSUE TITLE
Make system status problem text file display on the splash page.

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/splash_page#51]
This text will also display on the main menu of the web app.

**Comment by vjpsyverson** [comment]
Right now this file is at splash_page/assets/pages/alert.txt, but I can move it anywhere you think makes sense.

**Comment by jpjenk** [comment]
I have symlinked /Library/WebServer/pbdb-classic/message.txt to /Library/WebServer/pbdb-main/assets/pages/alert.txt on both teststrata and phylum. This required the creation of alert.txt on phylum and presumably will not work until the master branch of the splash page repo is brought up to date on this system.

Note: The messages are not linked across the two servers and must be edited directly on phylum in order to be seen on the production site. It's unlikely that we would want some special message just for the test rig so to avoid confusion we may want to remove alert.txt and message.txt from teststrata completely.
