### ISSUE TITLE
resource uploader

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/splash_page#52]
Need a page for uploading new resources, per education team.

**Comment by vjpsyverson** [comment]
@markuhen Ready for testing -- note that the Contribute button is just a mailto: link for now. I will improve it in later versions.

**Comment by markuhen** [comment]
Tested. See attached.

The email will need to be formatted as human readable text, and hopefully done in the background vs. being submitted by the sender who cold alter the message. 

[Uploader issues.pdf](https://github.com/paleobiodb/splash_page/files/1098843/Uploader.issues.pdf)

**Comment by markuhen** [comment]
I got a bounce back on the email. Is edu@paleobiodb.org not set up yet?

**Comment by vjpsyverson** [comment]
No, it isn't. I also can't read your last note -- it's cut off by the bottom of the pdf.

**Comment by markuhen** [comment]
I don't know what you mean about my "last note". All looks good on my end. Please clarify.

**Comment by vjpsyverson** [comment]
OK, as per your comments in the pdf, I fixed layout issues and added handling for multiple taxa. Going to dev in a couple minutes.

**Comment by vjpsyverson** [comment]
This has been moved to its own repo (resource_sub). The link to it is in the same place on splash page and I am closing this issue as finished.
