### ISSUE TITLE
Update ExCom people bubbles

### ISSUE THREAD

**Issue by mclapham** [paleobiodb/splash_page#62]
Now that the Executive Committee rotation has occurred, the the bouncing bubbles of doom on the "People" page need to be updated.

Remove from ExCom bubbles:
Roger Benson
Richard Butler
Matthew Carrano
Wolfgang Kiessling

Add to ExCom bubbles:
Phoebe Cohen
Patricia Holroyd
Jószef Pálfy

**Comment by vjpsyverson** [comment]
Updated on training; will be pushed with next splash page update at the end of this week.
